= ez-form

Forms for the web using hiccup. Tested with Hiccup and Replicant for
both Clojure and Clojurescript.

image::https://img.shields.io/clojars/v/ez-form.svg[https://clojars.org/ez-form,link=https://clojars.org/ez-form]

== defform

`defform` takes three arguments.

* `form-name` - The name of the form. This is used internally to keep
  track of which form is being used when the backend version is used
* `meta-opts` - This goes into the `:meta` keyword in the form for
  controlling how the form behaves
* `fielda`    - Which fields the form has

.Example usage
```clojure
(require '[clojures.string :as str])
(require '[ez-form.core :as form :refer [defform]])

(defn present [s]
  (not (str/blank? s)))

(defform myform
  {}
  [{:type       :text
    :label      "First name"
    :name       :firstname
    :attributes {:order 1} ;; additional parameters to add to the output HTML
    :validation [{:spec      present
                  :error-msg "First name must be present"}]}
   {:type       :text
    :label      "Last name"
    :name       :lastname
    :validation [{:spec      present
                  :error-msg "Last name must be present"}]}
   {:type       :email
    :name       :myemail
    :label      "My email"
    :validation [{:spec      present
                  :error-msg "Email must be present"}
                 {:spec      #(and (string? %)
                                   (str/contains? % "@"))
                  :error-msg "Email must contain a @ character"}]}])

;; the form as a table
(let [data       {:firstname "John"
                  :lastname  "Doe"
                  :email     "john.doe@example.com"}
      table-opts {:id    "myform"
                  :class ["table" "striped"]}]
  [:form {:method :post :action "/myform"}
   (form/as-table (myform data (:params request)) table-opts)
   [:input {:type :submit :value "Submit"}]])
```

== fields

Default supported fields are:

`:button`
`:checkbox`
`:color`
`:date`
`:datetime-local`
`:email`
`:file`
`:hidden`
`:month`
`:number`
`:password`
`:radio`
`:range`
`:reset`
`:search`
`:select`
`:submit`
`:tel`
`:text`
`:textarea`
`:time`
`:url`
`:week`

=== Extending fields

You can add new fields by specifying a `defform` with the following meta-option:

Here we add a shoelace web component for color picking.

```clojure

(defn sl-input-color-picker [{:keys [type attributes]}]
  [type attributes])

(defform myform
  {:extra-fields {:sl-color-picker sl-input-color-picker}}
  [{:name       ::color
    :type       :sl-color-picker
    :validation [{:spec      #(not (str/blank? %))
                  :error-msg [:div.error "Color must be picked"]}]}]}

```

== label and error messages

Default support for labels and error messages in as-table and as-template.


== helper functions

```clojure
;; will return a map of all the fields along with their associated values
(form/fields->map (myform nil (:params request))
 => {:firstname "Firstname", :lastname "Lastname", :myemail "firstname@lastname.com"}
```

== validation

Validation is done by spec as default. Validation is extendible. Each
new validation type will need a validate function that is 2-arity and
takes `field` and `value` as arguments.

Malli is supported out of the box.

== i18n

i18n is supported and does not have a default
implementation. link:../test/ez_form/i18n/m1p_test.clj[m1p],
link:../test/ez_form/i18n/tongue_test.clj[tongue] and
link:test/ez_form/i18n/tempura_test.clj[tempura] have implementation
examples in the test suite.

== Examples

There are example implementations in link:../dev/dev.clj[dev/dev.clj]

== License

Copyright © 2015-2025 Emil Bengtsson

Distributed under the MIT License.


---

Coram Deo
